modLoader="javafml"
loaderVersion="[30,)"
license="LGPL-3.0-only"
[[mods]]
modId="dm_suggestion_{#NUMBER}"
version="1.0.0"
displayName="DM Suggestion #{#NUMBER}"
displayURL="https://github.com/Bug1312/dm_suggestion_mods/tree/mod/{#NUMBER}"
authors="Bug1312"
description='''A mod that adds in suggestion #{#NUMBER} to Dalek Mod!'''

[[dependencies.dm_suggestion_{#NUMBER}]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dm_suggestion_{#NUMBER}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dm_suggestion_{#NUMBER}]]
    modId="dalekmod"
    mandatory=true
    versionRange="[68,)"
    ordering="NONE"
    side="BOTH"