modLoader="javafml"
loaderVersion="[30,)"
license="LGPL-3.0-only"
[[mods]]
modId="dm_suggestion_371"
version="1.0.0"
displayName="DM Suggestion #371"
displayURL="https://github.com/Bug1312/dm_suggestion_mods/tree/mod/371"
authors="Bug1312"
description='''A mod that adds in suggestion #371 to Dalek Mod!'''

[[dependencies.dm_suggestion_371]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dm_suggestion_371]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dm_suggestion_371]]
    modId="dalekmod"
    mandatory=true
    versionRange="[65.1.0,)"
    ordering="BEFORE"
    side="BOTH"