modLoader="javafml"
loaderVersion="[30,)"
license="LGPL-3.0-only"
[[mods]]
modId="dm_suggestion_194"
version="1.0.0"
displayName="DM Suggestion #194"
displayURL="https://github.com/Bug1312/dm_suggestion_mods/tree/mod/194"
authors="Bug1312"
description='''A mod that adds in suggestion #194 to Dalek Mod!'''

[[dependencies.dm_suggestion_194]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dm_suggestion_194]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dm_suggestion_194]]
    modId="dalekmod"
    mandatory=true
    versionRange="[65.1.0,)"
    ordering="NONE"
    side="BOTH"