modLoader="javafml"
loaderVersion="[30,)"
license="LGPL-3.0-only"
[[mods]]
modId="dm_suggestion_354"
version="1.0.0"
displayName="DM Suggestion #354"
displayURL="https://github.com/Bug1312/dm_suggestion_mods/tree/mod/354"
authors="Bug1312, Thermo DynAmics"
credits="Bug1312 - Programming | Thermo DynAmics - Art"
description='''A mod that adds in suggestion #354 to Dalek Mod!'''

[[dependencies.dm_suggestion_354]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dm_suggestion_354]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dm_suggestion_354]]
    modId="dalekmod"
    mandatory=true
    versionRange="[v65.0.0],[v65.0.1],[65.1.0,)"
    ordering="NONE"
    side="BOTH"